spring.application.name=Member

spring.datasource.url=${DB_URL1}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}


spring.thymeleaf.cache=false


spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
